name: erp_pos
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  form_field_validator: ^1.1.0
  provider: ^6.0.3
  pie_chart: ^5.3.2
  flutter_screenutil: ^5.5.3+2
  intl: ^0.17.0
  awesome_dialog: ^3.0.1
  dio: ^5.0.0
  crypto: ^3.0.2
  flutter_spinkit: ^5.1.0
  cool_alert: ^1.1.0
  shared_preferences: ^2.0.15
  sliding_up_panel: ^2.0.0+1
  jwt_decoder: ^2.0.1
  cached_network_image: ^3.2.1
  sqflite: ^2.2.2
  badges: ^3.0.2
  devla_sunmi: ^2.0.2
  codecamp_onepay: ^1.0.0
  qr_flutter: ^4.0.0
  get_ip_address: ^0.0.5
  device_info_plus: ^8.1.0
  jwt_decode: ^0.3.1
  google_nav_bar: ^5.0.6
  lite_rolling_switch: ^1.0.0
  pattern_formatter: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  like_button: ^2.0.5
  marquee: ^2.2.3
  get: ^4.6.5
  connectivity_plus: ^3.0.3
  internet_connection_checker: ^1.0.0+1

flutter_icons:
  android: true
  image_path: "images/Shape6.png"



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.0+1
  http: ^0.13.5
flutter_native_splash:
  image: "images/narharn.png"
  color: "#ffffff"
flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Phetsarath-OT
      fonts:
        - asset: fonts/Phetsarath-OT.ttf
 
