name: erp_pos
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  form_field_validator: ^1.1.0
  provider: ^6.0.3
  pie_chart: ^5.3.2
  flutter_screenutil: ^5.5.3+2
  intl: ^0.17.0
  awesome_dialog: ^2.2.1
  dio: ^4.0.6
  crypto: ^3.0.2
  flutter_spinkit: ^5.1.0
  cool_alert: ^1.1.0
  shared_preferences: ^2.0.15
  sliding_up_panel: ^2.0.0+1
  jwt_decoder: ^2.0.1
  cached_network_image: ^3.2.1
  sqflite: ^2.0.3+1
  badges: ^2.0.3
  devla_sunmi: ^2.0.2
  codecamp_onepay: ^1.0.0
  qr_flutter: ^4.0.0
  get_ip_address: ^0.0.5
  device_info_plus: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^1.3.3
  http: ^0.13.5
flutter_native_splash:
  image: "images/narharn.png"
  color: "#ffffff"
flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Phetsarath-OT
      fonts:
        - asset: fonts/Phetsarath-OT.ttf
 
